export interface Wand {
    owner: string;
    wood: string;
    length: string;
    core: string;
    flexibility: string;
}

export const wandsList = (): Wand[] => [
    {
        owner: "Albus Dumbledore",
        wood: "Elder",
        length: '15"',
        core: "Thestral tail hair",
        flexibility: "Unknown",
    },
    {
        owner: "Bellatrix Lestrange",
        wood: "Walnut",
        length: '12¾"',
        core: "Dragon heartstring",
        flexibility: "Unyielding",
    },
    {
        owner: "Sir Cadogan",
        wood: "Blackthorn",
        length: '9"',
        core: "Troll whisker",
        flexibility: "Combustible",
    },
    {
        owner: "Cedric Diggory",
        wood: "Ash",
        length: '12¼"',
        core: "Unicorn hair",
        flexibility: "Pleasantly springy",
    },
    {
        owner: "Celestina Warbeck",
        wood: "Larch",
        length: '10½"',
        core: "Phoenix feather",
        flexibility: "Flexible",
    },
    {
        owner: "Dolores Umbridge",
        wood: "Birch",
        length: '8"',
        core: "Dragon heartstring",
        flexibility: "Unknown",
    },
    {
        owner: "Draco Malfoy",
        wood: "Hawthorn",
        length: '10"',
        core: "Unicorn hair",
        flexibility: "Reasonably springy",
    },
    {
        owner: "Fleur Delacour",
        wood: "Rosewood",
        length: '9½"',
        core: "Veela hair",
        flexibility: "Inflexible",
    },
    {
        owner: "Garrick Ollivander",
        wood: "Hornbeam",
        length: '12¾"',
        core: "Dragon heartstring",
        flexibility: "Slightly bendy",
    },
    {
        owner: "Gilderoy Lockhart",
        wood: "Cherry",
        length: '9"',
        core: "Rougarou hair",
        flexibility: "Unknown",
    },
    {
        owner: "Harry Potter (wand #1)",
        wood: "Holly",
        length: '11"',
        core: "Phoenix feather",
        flexibility: "Nice and supple",
    },
    {
        owner: "Harry Potter (wand #2)",
        wood: "Blackthorn",
        length: '10"',
        core: "Unknown",
        flexibility: "Unknown",
    },
    {
        owner: "Hermione Granger",
        wood: "Vine",
        length: '10¾"',
        core: "Dragon heartstring",
        flexibility: "Unknown",
    },
    {
        owner: "Horace Slughorn",
        wood: "Cedar",
        length: '10¼"',
        core: "Dragon heartstring",
        flexibility: "Fairly flexible",
    },
    {
        owner: "James Potter",
        wood: "Mahogany",
        length: '11"',
        core: "Unknown",
        flexibility: "Pliable",
    },
    {
        owner: "Lily Evans",
        wood: "Willow",
        length: '10¼"',
        core: "Unknown",
        flexibility: "Swishy",
    },
    {
        owner: "Lucius Malfoy",
        wood: "Elm",
        length: '18"',
        core: "Dragon heartstring",
        flexibility: "Unknown",
    },
    {
        owner: "Mary Cattermole",
        wood: "Cherry",
        length: '8¾"',
        core: "Unicorn hair",
        flexibility: "Unknown",
    },
    {
        owner: "Merlin",
        wood: "Oak",
        length: "Unknown",
        core: "Unknown",
        flexibility: "Unknown",
    },
    {
        owner: "Minerva McGonagall",
        wood: "Fir",
        length: '9½"',
        core: "Dragon heartstring",
        flexibility: "Stiff",
    },
    {
        owner: "Neville Longbottom",
        wood: "Cherry",
        length: "Unknown",
        core: "Unicorn hair",
        flexibility: "Unknown",
    },
    {
        owner: "Peter Pettigrew",
        wood: "Chestnut",
        length: '9¼"',
        core: "Dragon heartstring",
        flexibility: "Brittle",
    },
    {
        owner: "Quirinus Quirrell",
        wood: "Alder",
        length: '9"',
        core: "Unicorn hair",
        flexibility: "Bendy",
    },
    {
        owner: "Remus Lupin",
        wood: "Cypress",
        length: '10¼"',
        core: "Unicorn hair",
        flexibility: "Pliable",
    },
    {
        owner: "Ron Weasley (wand #1)",
        wood: "Ash",
        length: '12"',
        core: "Unicorn hair",
        flexibility: "Unknown",
    },
    {
        owner: "Ron Weasley (wand #2)",
        wood: "Willow",
        length: '14"',
        core: "Unicorn hair",
        flexibility: "Unknown",
    },
    {
        owner: "Ron Weasley (wand #3)",
        wood: "Chestnut",
        length: '9¼"',
        core: "Dragon heartstring",
        flexibility: "Brittle",
    },
    {
        owner: "Rubeus Hagrid",
        wood: "Oak",
        length: '16"',
        core: "Unknown",
        flexibility: "Rather bendy",
    },
    {
        owner: "Silvanus Kettleburn",
        wood: "Chestnut",
        length: '11½"',
        core: "Phoenix feather",
        flexibility: "Whippy",
    },
    {
        owner: "Tom Riddle",
        wood: "Yew",
        length: '13½"',
        core: "Phoenix feather",
        flexibility: "Unknown",
    },
    {
        owner: "Viktor Krum",
        wood: "Hornbeam",
        length: '10¼"',
        core: "Dragon heartstring",
        flexibility: "Quite rigid",
    },
    {
        owner: "Ginny Weasley",
        wood: "Yew",
        length: "Unknown",
        core: "Unknown",
        flexibility: "Unknown",
    },
    {
        owner: "Sybill Trelawney",
        wood: "Hazel",
        length: '9½"',
        core: "Unicorn hair",
        flexibility: "Very flexible",
    },
    {
        owner: "Dylan Marwood",
        wood: "Applewood",
        length: "Unknown",
        core: "Unknown",
        flexibility: "Unknown",
    },
    {
        owner: "The Silver Spears",
        wood: "Aspen",
        length: "Unknown",
        core: "Unknown",
        flexibility: "Unknown",
    },
    {
        owner: "Eldritch Diggory",
        wood: "Poplar",
        length: "Unknown",
        core: "Unknown",
        flexibility: "Fine",
    },
    {
        owner: "Evangeline Orpington",
        wood: "Unknown",
        length: "Unknown",
        core: "Unknown",
        flexibility: "Unknown",
    },
    {
        owner: "Wands produced by Garrick Ollivander",
        wood: "Beechwood",
        length: '9"',
        core: "Dragon heartstring",
        flexibility: "Nice and flexible",
    },
    {
        owner: "Mad-Eye Moody",
        wood: "Maple",
        length: '7"',
        core: "Phoenix feather",
        flexibility: "Quite whippy",
    },
    {
        owner: "Kaitie Bell",
        wood: "Ebony",
        length: '8½"',
        core: "Unicorn hair",
        flexibility: "Springy",
    },
    {
        owner: "Percy Weasley",
        wood: "Apple",
        length: '9"',
        core: "Dragon heartstring",
        flexibility: "Rigid",
    },
    {
        owner: "Jacob",
        wood: "Maple",
        length: '10"',
        core: "Dragon heartstring",
        flexibility: "Fine",
    },
    {
        owner: "Jacob's sibling (wand #1)",
        wood: "Maple",
        length: '14"',
        core: "Unicorn hair",
        flexibility: "Reasonably springy",
    },
    {
        owner: "Luna Lovegood",
        wood: "Acacia",
        length: '12"',
        core: "Unicorn hair",
        flexibility: "Pliable",
    },
    {
        owner: "Fred Weasley",
        wood: "Hornbeam",
        length: '11"',
        core: "Dragon heartstring",
        flexibility: "Inflexible",
    },
    {
        owner: "Dean Thomas",
        wood: "Blackthorn",
        length: '11¼"',
        core: "Unicorn hair",
        flexibility: "Slightly springy and flexible",
    },
    {
        owner: "Jacob's sibling (wand #2)",
        wood: "Ebony",
        length: '11¼"',
        core: "Dragon heartstring",
        flexibility: "Unknown",
    },
    {
        owner: "Newton Scamander",
        wood: "Redwood",
        length: '11"',
        core: "Unicorn hair",
        flexibility: "Unknown",
    },
    {
        owner: "Lavender Brown",
        wood: "Laurel",
        length: '12"',
        core: "Phoenix feather",
        flexibility: "Unknown",
    },
    {
        owner: "Chadwick Boot",
        wood: "Prickly Ash",
        length: "Unknown",
        core: "Horned Serpent Horn",
        flexibility: "Unknown",
    },
    {
        owner: "Webster Boot",
        wood: "Unknown",
        length: "Unknown",
        core: "Horned Serpent Horn",
        flexibility: "Unknown",
    },
    {
        owner: "Salazar Slytherin",
        wood: "Unknown",
        length: "Unknown",
        core: "Basilisk horn",
        flexibility: "Unknown",
    },
];
